# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: final_task_development
  pool: 10
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: final_task_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: final_task_production
  pool: 5
  username: postgres
  password: postgres